[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Dependencies
remappings = [
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

# Add optimizer settings
optimizer = true
optimizer_runs = 200

sender = "0x24962D83f3eB5F18f159A24e4354078780314729"
private_key = "${PRIVATE_KEY}"

# Default network
default_network = "monad"

[rpc_endpoints]
monad = "https://testnet-rpc.monad.xyz"


# Monad Configuration
eth-rpc-url="https://testnet-rpc.monad.xyz"
chain_id = "10143"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
